// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addChirp = `-- name: AddChirp :many
INSERT INTO chirps ( id, created_at, updated_at, body, user_id) 
VALUES ( gen_random_uuid(), NOW(), NOW(), $1, $2 )
RETURNING id, created_at, updated_at, body, user_id
`

type AddChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) AddChirp(ctx context.Context, arg AddChirpParams) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, addChirp, arg.Body, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChirp = `-- name: DeleteChirp :exec
DELETE FROM chirps
WHERE id=$1 AND 
user_id=$2
`

type DeleteChirpParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirp(ctx context.Context, arg DeleteChirpParams) error {
	_, err := q.db.ExecContext(ctx, deleteChirp, arg.ID, arg.UserID)
	return err
}

const getAllChirps = `-- name: GetAllChirps :many
SELECT id, created_at, updated_at, body, user_id 
FROM chirps 
ORDER BY 
    CASE WHEN $1::text='asc' THEN created_at END ASC,
    CASE WHEN $1::text='desc' THEN created_at END DESC
`

func (q *Queries) GetAllChirps(ctx context.Context, sortOrder string) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirps, sortOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChirp = `-- name: GetChirp :one
SELECT id, created_at, updated_at, body, user_id FROM chirps WHERE id=$1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getChirpsForAuthor = `-- name: GetChirpsForAuthor :many
SELECT id, created_at, updated_at, body, user_id 
FROM chirps 
WHERE user_id=$1 
ORDER BY 
    CASE WHEN $2::text='asc' THEN created_at END ASC,
    CASE WHEN $2::text='desc' THEN created_at END DESC
`

type GetChirpsForAuthorParams struct {
	UserID    uuid.UUID
	SortOrder string
}

func (q *Queries) GetChirpsForAuthor(ctx context.Context, arg GetChirpsForAuthorParams) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getChirpsForAuthor, arg.UserID, arg.SortOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
